
services:
  frontend-angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    depends_on:
      - backend-dotnet
    environment:
      - API_BASE_URL=http://localhost:8080
    networks:
      - intelliinspect-network

  backend-dotnet:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      - ml-service-python
    environment:
      - ML_SERVICE_URL=http://ml-service-python:8000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - intelliinspect-network

  ml-service-python:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    networks:
      - intelliinspect-network

networks:
  intelliinspect-network:
    driver: bridge

volumes:
  data:
